---
name: CI

on:
    push:
        branches:
            - development
            - stable
    pull_request:
    schedule:
        - cron: 0 0 * * 0 # weekly

jobs:
    bazel_test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.6, 3.7, 3.8, 3.9]
                exclude:
                    # Only test recent python versions on macOS.
                    - os: macos-latest
                      python: 3.6
                    - os: macos-latest
                      python: 3.7

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install dependencies (linux)
              run: |
                  curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64" > bazel
                  chmod +x bazel
                  sudo mv bazel /usr/local/bin/bazel
                  sudo apt install clang-9 patchelf
                  python -m pip install -r compiler_gym/requirements.txt -r examples/requirements.txt -r tests/requirements.txt
              if: matrix.os == 'ubuntu-latest'

            - name: Install dependencies (macOS)
              run: |
                  brew install bazelisk zlib
                  python -m pip install -r compiler_gym/requirements.txt -r examples/requirements.txt -r tests/requirements.txt
              env:
                  LDFLAGS: -L/usr/local/opt/zlib/lib
                  CPPFLAGS: -I/usr/local/opt/zlib/include
                  PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig
              if: matrix.os == 'macos-latest'

            - name: Test
              run: make test
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_TEST_OPTS: --config=ci --test_timeout=300,900,1800,7200


    install_test:
        runs-on: ${{ matrix.os }}

        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest]
                python: [3.8]

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python ${{ matrix.python }}
              uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install dependencies (linux)
              run: |
                  curl -L "https://github.com/bazelbuild/bazelisk/releases/download/v1.6.1/bazelisk-linux-amd64" > bazel
                  chmod +x bazel
                  sudo mv bazel /usr/local/bin/bazel
                  sudo apt install clang-9 patchelf
                  python -m pip install -r compiler_gym/requirements.txt -r examples/requirements.txt -r tests/requirements.txt
              if: matrix.os == 'ubuntu-latest'

            - name: Install dependencies (macos)
              run: |
                  brew install bazelisk zlib
                  python -m pip install -r compiler_gym/requirements.txt -r examples/requirements.txt -r tests/requirements.txt
              env:
                  LDFLAGS: -L/usr/local/opt/zlib/lib
                  CPPFLAGS: -I/usr/local/opt/zlib/include
                  PKG_CONFIG_PATH: /usr/local/opt/zlib/lib/pkgconfig
              if: matrix.os == 'macos-latest'

            - name: Install
              run: make install
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Test
              run: make install-test
              env:
                  CC: clang
                  CXX: clang++
                  BAZEL_BUILD_OPTS: --config=ci

            - name: Uninstall
              run: make purge
